blogdjango/urls.py
# Static files configuration
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import include, url
from django.urls import re_path, path
from django.contrib import admin

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('comments.urls')),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('', include('posts.urls')),
    path('api/posts/', include("posts.api.urls")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin
from django.urls import re_path

from .views import (
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
)
app_name='posts'
urlpatterns = [
    re_path(r'^$', post_list, name='list'),
    re_path(r'^create/$', post_create),
    re_path(r'^(?P<slug>[-\w]+)/$', post_detail, name='detail'),
    re_path(r'^(?P<slug>[-\w]+)/edit/$', post_update, name='update'),
    re_path(r'^(?P<id>\d+)/delete/$', post_delete),
]

posts/models.py
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save

from django.utils.safestring import mark_safe
from django.utils import timezone
from django.utils.text import slugify

from .utils import get_read_time


from markdown_deux import markdown
from comments.models import Comment
# Create your models here.
 #MVC MODEL VIEW CONTROLLER

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() * super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
    return "%s/%s" %(id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
            null=True, 
            blank=True,
            width_field="width_field",
            height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.IntegerField(default=0) # models.TimeField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()


    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})
        # return "/posts/%s/" %(self.id)
    
    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)
    
    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs
    
    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type
        
def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwagrs):
    if not instance.slug:
        instance.slug = create_slug(instance)
    
    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var

pre_save.connect(pre_save_post_receiver, sender=Post)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.min.css">
    <link rel="stylesheet" href='{% static "css/base.css" %}'>
    <title>{% block head_title %}Try Django 1.9{% endblock head_title %}</title>
    {% block head_extra %} {% endblock head_extra%}
</head>
<body>

  <div class="fb-root"></div>
  <script>(function(d,s,id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_us/sdk.js#xfbml=1&version=v2.5";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

    {% include "messages_display.html" %}

    <div class="container">
      <ul class="breadcrumb">
        <li><a href='{% url "posts:list" %}'>Home</a></li>
        {% block post_detail_link %}
        {% endblock %}
        {% if request.user.is_authenticated %}
        <li class="pull-right"><a href='{% url "logout" %}'>Logout</a></li>
        {% else %}
        <li class="pull-right"><a href='{% url "register" %}'>Register</a></li>
        <li class="pull-right"><a href='{% url "login" %}'>Login</a></li>
        {% endif %}    
      </ul>
      {% block content %} {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-1.12.2.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function(){

        $(".content-markdown").each(function(){
          var content = $(this).text()
          var markedContent = marked(content)
          $(this).html(markedContent);
        })
        
        $(".post-detail-item img").each(function(){
          $(this).addClass("img-responsive");
        })

     

        var contentInput = $("#id_content")
        function setContent(value){
          var markedContent = marked(value)
          $("#preview-content").html(markedContent)
          $("#preview-content img"). each(function(){
            $(this).addClass("img-responsive")
          }) 
        }

        setContent(contentInput.val())

        contentInput.keyup(function(){
          var newContent = $(this).val()
          setContent(newContent)
        })

        var titleInput = $("#id_title");

        function setTitle(value){
          $("#preview-title").text(value)
        }
        setTitle(titleInput.val())

        titleInput.keyup(function(){
          var newContent = $(this).val()
          setTitle(newContent)
        })

        $(".comment-reply-btn").click(function(event){
          event.preventDefault();
          $(this).parent().next(".comment-reply").fadeToggle();
        })

      })
    </script>
</body>
</html>

templates/create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
  {{ form.media }}
{% endblock head_extra %}

{% block content %}

<div class="col-sm-6">
  <h1>Preview</h1>
  <br>
    <div id="content-preview">
      <h3 id="preview-title"></h3>
      <p id="preview-content"></p>
    </div>
</div>

<div class="col-sm-6">
  <h1>Form</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success" value="Create Post">
  </form>
</div>
{% endblock content %}

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-sm-6 col-sm-offset-3">
  <h1>{{ title }}</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success" value="{{ title }}">
  </form>
</div>
{% endblock content %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Template is working</title>
</head>
<body>
    <h1>{{ title }}</h1>
    
    {% for obj in object_list %}
     <a href="{{ obj.get_absolute_url }}"> {{ obj.title }} <br></a>
      {{ obj.content }} <br>
      {{ obj.timestamp }} <br>
      {{ obj.updated }} <br>
      <br>
    {% endfor %}
</body>
</html>

templates/messages_display.html
{% if messages %}
  <div class="messages">
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
      {% endfor %}
    </ul>
  </div>
{% endif %}

templates/post_list.html
{% extends "base.html" %}
{% block content %}

<div class="col-sm-6 col-sm-offset-3">
  <h1>{{ title }}</h1>
  <form class="row" method="GET" action="">
    <div class="col-sm-6">
      <div class="input-group">
        <input class="form-control" type="text" name="q" placeholder="Search posts" value="{{ request.GET.q }}">
        <span class="input-group-btn">
          
          <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
        </span>
    </div>
  </div>
  </form>
  {% for obj in object_list %}
    <div class="row">
      <div class="col-sm-12">
        <div class="thumbnail">
        {% if obj.image %}
          <img src="{{ obj.image.url }}" alt="">
        {% endif %}
          <div class="caption post-detail-item">
          {% if obj.draft %}<h3>Staff Only: Draft</h3>{% endif %}
          {% if obj.publish > today %} <h3>Future post</h3> {% endif %}
            <h3>
              <a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a><small> {{ obj.publish | timesince }} ago</small>
            </h3>
            <p>{% if obj.user.get_full_name %}Author: {{ obj.user.get_full_name }}{% endif %}</p>
            {{ obj.get_markdown|safe }}
            <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
          </div>
        </div>
      </div>
      <hr>
    </div>
  {% endfor %}

  <div class="pagination">
    <span class="step-links">
      {% if object_list.has_previous %}
        <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a>
      {% endif %}

      <span class="current">
        Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}
      </span>

      {% if object_list.has_next %}
        <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a>
      {% endif %}


    </span>
  </div>

</div>


{% endblock content %}